server.port: 8090

spring:
  liquibase:
    change-log: classpath:/liquibase/master.yml
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_rating?currentSchema=public
    username: postgres
    password: postgres
  threads:
    virtual:
      enabled: true